.TH SEACAS 1 "May 5, 2014"
.SH NAME
SEACAS - Sandia Engineering Analysis Code Access System
.SH SYNOPSIS
.B seacas-fastq
.br
.B seacas-mapva
.br
.B seacas-aprepr
.br
.B seacas-grop
.br
.B seacas-decom
.br
.B seacas-sphge
.br
.B seacas-gen3
.br
.B seacas-exodif
.br
.B seacas-blo
.br
.B seacas-algebr
.br
.B seacas-io_shell
.br
.B seacas-genshell
.br
.B seacas-exomatlab
.br
.B seacas-io_info
.br
.B seacas-grepos
.br
.B seacas-shell_to_hex
.br
.B seacas-nem_spread
.br
.B seacas-mat2exo
.br
.B seacas-numbers
.br
.B seacas-mapvar-kd
.br
.B seacas-cth_pressure_map
.br
.B seacas-exotxt
.br
.B seacas-ejoin
.br
.B seacas-txtexo
.br
.B seacas-epu
.br
.B seacas-gjoin
.br
.B seacas-nem_slice
.br
.B seacas-exo2mat
.br
.B seacas-conjoin
.SH DESCRIPTION
The Sandia Engineering Analysis Code Access System (SEACAS) is a suite of \
preprocessing, postprocessing, translation, and utility applications \
supporting finite element analysis software using the ExodusII database file \
format.
.PP
.SH ENVIRONMENT
Add /usr/lib/seacas to your PATH to get access to the non-prefixed commands.
.PP
.SH SEE ALSO
/usr/share/doc/seacas/
.SH AUTHOR
SEACAS was written by Gregory Sjaardema at Sandia Labs <http://http://trilinos.sandia.gov/>. \
This manual page was written by Felix Salfelder <felix@salfelder.org>.
